### ISSUE TITLE
Recipe for creating and aligning an atlas

### ISSUE THREAD

**Issue by eddyod** [ActiveBrainAtlasPipeline/center_of_mass#1]
Replicate this recipe:

https://github.com/ActiveBrainAtlasPipeline/center_of_mass

**Comment by Junjie-Cheng** [comment]
1. The aws s3 is not available to people without credentials. I commented out the instructions for now and re-organized the steps.
2. The tarball file contains two folders with 51 files each (`structures` and `origin`), but there are two empty folders, `atlas` and `mesh`. We need to fix this.
3. The `requirements.txt` file seems to have excess and conflicting entries. It also misses some required packages like `neruoglancer`. I updated the file to include the dependencies needed, but we may need to remove the unused/conflicting package requirements in the future.
4. I have updated the scripts that hardcoded the birdstore locations. I also updated the README.md so the user can copy from the code snippet and run directly.
5. I am able to load the precomputed data into neuroglancer and it looks just like the atlasV7 layers in our stored urls, except that some components are missing. I am wondering whether the tarball contains the right data, as the generated atlas in neuroglancer seems missing some components.
6. For the alignment, I am not sure which brain data it refers and I am unable to check the rotation matrix works the way we want (although it should be right according to our tests on neuroglancer). Seems that `7n_R` in the readme file should be `7N_R`. I updated the readme file to upper case `N`s for now. Correct me if it is wrong.

### Things to do/discuss
1. Confirm that the tarball has the right data
2. Do the users need the flexibility to generate neuroglancer precomputed data/alignment on different atlas structures? If so, I can make an option to specify the atlas path.
3. Do the users need the flexibility to use a file like csv, JSON, etc for the `reference_centers`?

**Comment by eddyod** [comment]
Junjie,
Thanks for doing all that testing. I fixed a big bug with the missing structures. Yes, that aws is not very helpful so using curl or wget is fine.
Do a git pull and try rebuilding again. They should look good. As for your 'Things to discuss' points 2 and 3 above I don't think that is necessary. Can you email when you have built the atlas.  And don't worry about the alignment as they will have to use their own images. Thanks!

**Comment by Junjie-Cheng** [comment]
Hi @eddyod 
I tested the new script and I think it is good.
I happened to test the rotation matrix API on the atlasV7 layer aligning to DK52 by calling the API on `/ng_test/` and I noticed the output matrix is a little bit different than the one in `Altas, DK39premotor, DK52 PM Nucleus`. Is that normal?

**Comment by eddyod** [comment]
@Junjie-Cheng 
I updated and feel confident with it. Let me know when you have tested again. I had to update the requirements.txt file.

**Comment by Junjie-Cheng** [comment]
Hi @eddyod 
The `requirements.txt` file works fine, I need to update the readme and the path variables in the script as the structure of atlas tarball has changed. I am still having a little bit issue with the center of mass script, can we zoom now?

**Comment by Junjie-Cheng** [comment]
Hi @eddyod 
Update: I was able to reproduce the same result returned from the API call by supplying the data from the database to `center_of_mass.py`. Since we haven't changed the API code, which produced really good result before, I believe that the script should be correct, and our code should be good to use.

**However**, even with the updated `5N_L` and `5N_R` values, the rotation matrix doesn't really fit the atlas into DK39. I suspect that the center of mass data is still not accurate.
I also tried the MD589. It seems that the data in the email is different than the one in the database. And it seems that the matrix from neither sources fit the atlas well.
Can we confirm the accuracy of the center of mass data we have?

**Comment by eddyod** [comment]
@Junjie-Cheng 
Lets meet today, can you do 3pm (10 dec)?

**Comment by Junjie-Cheng** [comment]
@eddyod Sure let’s meet at 3
